server:
  port: 8080

spring:
  application:
    name: user-service

  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGO_URI}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  swagger-ui:
    path: /exa-tec-doc

copomex:
  api:
    key: ${COPOMEX_API_KEY}

